name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install dependencies
      run: yarn install

    - name: Run all tests
      run: yarn test

    - name: Build production files
      run: yarn build
      env:
        PUBLIC_URL: https://githiago-f.github.io/about-me/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
